name: build and deploy

on:
  push:
    branches: [ "main" ]
    paths-ignore:
      - '.github/workflows/**'
  pull_request:
    branches: [ "main" ]
    paths-ignore:
      - '.github/workflows/**'

env:
  ARM_CLIENT_ID: ${{ vars.ARM_CLIENT_ID }}
  ARM_CLIENT_SECRET: ${{ vars.ARM_CLIENT_SECRET }}
  ARM_TENANT_ID: ${{ vars.ARM_TENANT_ID }}
  ARM_SUBSCRIPTION_ID: ${{ vars.ARM_SUBSCRIPTION_ID }}

jobs:
  CICD:
    name: Build and Deploy Application to Azure
    runs-on: ubuntu-latest
  
    steps:

    - name: Checkout code
      uses: actions/checkout@v2

    - name: Azure Login
      uses: Azure/login@v2.2.0
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Azure set subscription
      run: az account set --subscription ${{ vars.ARM_SUBSCRIPTION_ID }}

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2.0.3
    
    - name: Terraform Init
      run: terraform init
      working-directory: ./Terraform
    
    - name: Terraform Apply
      run: terraform apply -auto-approve
      working-directory: ./Terraform

    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-image-name:{GITHUB_RUN_NUMBER}
      working-directory: ./terraform-poc-ui
